// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKQrUKXjqSf3CcfH2oaQ5yrPUC2a52tAs',
    appId: '1:914502595800:web:0ec3375af004cc4f7fd3ad',
    messagingSenderId: '914502595800',
    projectId: 'chitti-project-11fab',
    authDomain: 'chitti-project-11fab.firebaseapp.com',
    databaseURL: 'https://chitti-project-11fab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chitti-project-11fab.firebasestorage.app',
    measurementId: 'G-GVXBLBSVVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB84-rmRNwO0V9DpBMksqhz_C7ouMhG7c',
    appId: '1:914502595800:android:6871780d5715c8077fd3ad',
    messagingSenderId: '914502595800',
    projectId: 'chitti-project-11fab',
    databaseURL: 'https://chitti-project-11fab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chitti-project-11fab.firebasestorage.app',
  );
}
