import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:chitt/services/settings_service.dart';
import 'package:chitt/services/chitti_name_generator.dart';
import 'package:chitt/screens/verify_chitti_screen.dart';
import 'package:chitt/core/models/gold_option.dart';
import 'package:chitt/utils/currency_utils.dart';

class CreateChittiScreen extends StatefulWidget {
  final Map<String, dynamic>? chittiData; // null = create, non-null = edit

  const CreateChittiScreen({super.key, this.chittiData});

  @override
  State<CreateChittiScreen> createState() => _CreateChittiScreenState();
}

class _CreateChittiScreenState extends State<CreateChittiScreen> {
  late TextEditingController _nameController;
  int _duration = 12;
  static const int _minDuration = 1;
  static const int _maxDuration = 120;
  late TextEditingController _maxSlotsController;
  String _selectedStartMonth = DateFormat('MMMM yyyy').format(DateTime.now());

  // New Configuration Fields
  String _paymentDay = '5';
  String _luckyDrawDay = '10';

  // Per-gold-option reward configuration
  final Map<String, bool> _goldOptionRewardEnabled = {};
  final Map<String, String> _goldOptionRewardType = {};
  final Map<String, TextEditingController> _goldOptionRewardControllers = {};

  // Gold Options - NEW Enhanced Structure
  final List<GoldOption> _selectedGoldOptions = [];
  List<GoldOption> _availableGoldOptions = []; // From DB
  final Map<String, TextEditingController> _goldOptionTotalCostControllers = {};
  List<String> _goldTypes = [];
  List<String> _goldPurities = [];

  // Chitti name auto-generation
  Map<String, dynamic>? _appSettings;
  bool _nameAutoGenerated = false;

  // Edit mode helpers
  bool get isEditMode => widget.chittiData != null;
  String? get chittiId => widget.chittiData?['id'];

  @override
  void initState() {
    super.initState();

    // Initialize controllers with default or pre-filled values
    if (isEditMode) {
      _initializeForEdit();
    } else {
      _initializeForCreate();
    }

    _nameController.addListener(() {
      if (_nameAutoGenerated) {
        _nameAutoGenerated = false;
      }
    });
    _loadAppSettings();
  }

  void _initializeForCreate() {
    _nameController = TextEditingController(text: 'Gold Chitti');
    _maxSlotsController = TextEditingController(text: '70');
  }

  void _initializeForEdit() {
    final data = widget.chittiData!;

    // DEBUG: Print all data to identify null values
    print('DEBUG _initializeForEdit: data keys = ${data.keys.toList()}');
    print('DEBUG _initializeForEdit: name = ${data['name']}');
    print('DEBUG _initializeForEdit: duration = ${data['duration']}');
    print('DEBUG _initializeForEdit: goldOptionsV2 = ${data['goldOptionsV2']}');
    print('DEBUG _initializeForEdit: goldOptions = ${data['goldOptions']}');
    print('DEBUG _initializeForEdit: purityPrices = ${data['purityPrices']}');
    print(
      'DEBUG _initializeForEdit: goldOptionRewards = ${data['goldOptionRewards']}',
    );
    print('DEBUG _initializeForEdit: startMonth = ${data['startMonth']}');
    print('DEBUG _initializeForEdit: paymentDay = ${data['paymentDay']}');
    print('DEBUG _initializeForEdit: luckyDrawDay = ${data['luckyDrawDay']}');
    print('DEBUG _initializeForEdit: maxSlots = ${data['maxSlots']}');

    _nameController = TextEditingController(text: data['name'] ?? '');

    // Parse duration
    final rawDuration = data['duration'];
    if (rawDuration != null) {
      _duration = int.tryParse(rawDuration.toString()) ?? 12;
    }
    // Clamp duration to valid range
    _duration = _duration.clamp(_minDuration, _maxDuration);

    // Extract gold options from goldOptionsV2 or legacy goldOptions
    final rawOptionsV2 = data['goldOptionsV2'] as List?;
    if (rawOptionsV2 != null && rawOptionsV2.isNotEmpty) {
      // New format
      for (var opt in rawOptionsV2) {
        if (opt == null) continue; // Skip null entries
        try {
          final goldOption = GoldOption.fromMap(
            Map<String, dynamic>.from(opt as Map),
          );
          if (!_selectedGoldOptions.any((o) => o.id == goldOption.id)) {
            _selectedGoldOptions.add(goldOption);
          }
        } catch (e) {
          print('DEBUG: Error parsing gold option: $e');
        }
      }
      // Extract total costs per option (from goldOptions legacy format)
      final goldOptions = data['goldOptions'] as List?;
      if (goldOptions != null) {
        for (
          int i = 0;
          i < _selectedGoldOptions.length && i < goldOptions.length;
          i++
        ) {
          final opt = goldOptions[i] as Map?;
          if (opt != null) {
            final totalValue = (opt['total_value'] ?? 0).toDouble();
            _goldOptionTotalCostControllers[_selectedGoldOptions[i].id] =
                TextEditingController(
                  text: totalValue > 0 ? totalValue.toStringAsFixed(0) : '',
                )..addListener(() => setState(() {}));
          }
        }
      }
    } else {
      // Legacy format - try to convert
      final rawOptions = data['goldOptions'] as List? ?? [];
      final options = <Map<String, dynamic>>[];
      for (var e in rawOptions) {
        if (e == null) continue;
        try {
          options.add(Map<String, dynamic>.from(e as Map));
        } catch (_) {
          // Skip invalid entries
        }
      }

      if (options.isNotEmpty) {
        for (var opt in options) {
          // Parse weight - handle both numeric and string formats like "5g"
          num weight = 0;
          final weightVal = opt['weight'] ?? opt['grams'];
          if (weightVal is num) {
            weight = weightVal;
          } else if (weightVal is String) {
            weight = num.tryParse(weightVal.replaceAll('g', '').trim()) ?? 0;
          }

          if (weight > 0) {
            // Extract actual type and purity from data
            final type = opt['type']?.toString() ?? 'Coin';
            final purity = opt['purity']?.toString() ?? '22 Karat';

            final legacyOption = GoldOption(
              id: GoldOption.generateId(),
              type: type,
              purity: purity,
              weight: weight,
            );
            _selectedGoldOptions.add(legacyOption);
          }
        }

        // Create total cost controllers from legacy data
        for (
          var i = 0;
          i < _selectedGoldOptions.length && i < options.length;
          i++
        ) {
          final opt = options[i];
          final totalValue = (opt['total_value'] ?? 0).toDouble();
          _goldOptionTotalCostControllers[_selectedGoldOptions[i].id] =
              TextEditingController(
                text: totalValue > 0 ? totalValue.toStringAsFixed(0) : '',
              )..addListener(() => setState(() {}));
        }
      }
    }

    _maxSlotsController = TextEditingController(
      text: '${data['maxSlots'] ?? 70}',
    );
    _selectedStartMonth =
        data['startMonth'] ?? DateFormat('MMMM yyyy').format(DateTime.now());
    _paymentDay = '${data['paymentDay'] ?? 5}';
    _luckyDrawDay = '${data['luckyDrawDay'] ?? 10}';

    // Load per-option rewards
    final goldOptionRewards = data['goldOptionRewards'] as Map?;
    if (goldOptionRewards != null && goldOptionRewards.isNotEmpty) {
      // Get the reward keys in order
      final rewardKeys = goldOptionRewards.keys.toList();

      // Match rewards by position since legacy options get new IDs
      for (int i = 0; i < _selectedGoldOptions.length; i++) {
        final option = _selectedGoldOptions[i];

        // First try to find by exact ID match
        Map? rewardConfig = goldOptionRewards[option.id] as Map?;

        // If not found by ID, try to match by position
        if (rewardConfig == null && i < rewardKeys.length) {
          rewardConfig = goldOptionRewards[rewardKeys[i]] as Map?;
        }

        if (rewardConfig != null) {
          _goldOptionRewardEnabled[option.id] =
              rewardConfig['enabled'] ?? false;
          _goldOptionRewardType[option.id] =
              rewardConfig['type'] ?? 'Fixed Amount';
          _goldOptionRewardControllers[option.id] = TextEditingController(
            text:
                (rewardConfig['value'] ?? rewardConfig['calculatedAmount'] ?? 0)
                    .toString(),
          )..addListener(() => setState(() {}));
        }
      }
    } else {
      // Handle legacy global rewardConfig
      final legacyRewardConfig = data['rewardConfig'] as Map?;
      if (legacyRewardConfig != null && legacyRewardConfig['enabled'] == true) {
        // Apply legacy reward to all selected gold options
        for (var option in _selectedGoldOptions) {
          _goldOptionRewardEnabled[option.id] = true;
          _goldOptionRewardType[option.id] =
              legacyRewardConfig['type'] ?? 'Fixed Amount';
          _goldOptionRewardControllers[option.id] = TextEditingController(
            text: (legacyRewardConfig['value'] ?? 0).toString(),
          )..addListener(() => setState(() {}));
        }
      }
    }
  }

  Future<void> _loadAppSettings() async {
    final settings = await SettingsService().getAppSettings();
    final goldOptions = await SettingsService().getGoldOptionsV2();
    final goldTypes = await SettingsService().getGoldTypes();
    final goldPurities = await SettingsService().getGoldPurities();
    setState(() {
      _appSettings = settings;
      _availableGoldOptions = goldOptions;
      _goldTypes = goldTypes;
      _goldPurities = goldPurities;
    });
    // Only auto-generate name in create mode
    if (!isEditMode) {
      _generateChittiName();
    }
  }

  Future<void> _generateChittiName() async {
    if (_appSettings == null) return;

    final generator = ChittiNameGenerator();
    final generatedName = await generator.generateNextName(
      appSettings: _appSettings!,
      duration: _duration,
      startMonth: _selectedStartMonth,
    );

    setState(() {
      _nameController.text = generatedName;
      _nameAutoGenerated = true;
    });
  }

  @override
  void dispose() {
    _nameController.dispose();
    _maxSlotsController.dispose();
    // Dispose all total cost controllers
    for (var controller in _goldOptionTotalCostControllers.values) {
      controller.dispose();
    }
    // Dispose all reward controllers
    for (var controller in _goldOptionRewardControllers.values) {
      controller.dispose();
    }
    super.dispose();
  }

  String _calculateEndMonth() {
    // Parse "January 2024" format
    final parts = _selectedStartMonth.split(' ');
    if (parts.length != 2) return _selectedStartMonth;

    const months = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];
    final monthIndex = months.indexOf(parts[0]);
    final year = int.tryParse(parts[1]) ?? DateTime.now().year;

    if (monthIndex == -1) return _selectedStartMonth;

    final endMonthIndex = (monthIndex + _duration - 1) % 12;
    final endYear = year + ((monthIndex + _duration - 1) ~/ 12);

    return '${months[endMonthIndex]} $endYear';
  }

  void _showAddGoldOptionDialog() {
    String? selectedType = _goldTypes.isNotEmpty ? _goldTypes.first : null;
    String? selectedPurity = _goldPurities.isNotEmpty
        ? _goldPurities.first
        : null;
    final weightController = TextEditingController();

    showDialog(
      context: context,
      builder: (context) => StatefulBuilder(
        builder: (context, setDialogState) => AlertDialog(
          title: Text(
            'Add Gold Option',
            style: GoogleFonts.inter(fontWeight: FontWeight.w600),
          ),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Type Dropdown
              Text(
                'Gold Type',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: Theme.of(
                    context,
                  ).colorScheme.onSurface.withOpacity(0.7),
                ),
              ),
              const SizedBox(height: 6),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 12),
                decoration: BoxDecoration(
                  border: Border.all(
                    color: Theme.of(context).colorScheme.outline,
                  ),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: DropdownButtonHideUnderline(
                  child: DropdownButton<String>(
                    value: selectedType,
                    isExpanded: true,
                    items: _goldTypes.map((type) {
                      return DropdownMenuItem(value: type, child: Text(type));
                    }).toList(),
                    onChanged: (val) {
                      setDialogState(() => selectedType = val);
                    },
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Purity Dropdown
              Text(
                'Purity',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: Theme.of(
                    context,
                  ).colorScheme.onSurface.withOpacity(0.7),
                ),
              ),
              const SizedBox(height: 6),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 12),
                decoration: BoxDecoration(
                  border: Border.all(
                    color: Theme.of(context).colorScheme.outline,
                  ),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: DropdownButtonHideUnderline(
                  child: DropdownButton<String>(
                    value: selectedPurity,
                    isExpanded: true,
                    items: _goldPurities.map((purity) {
                      return DropdownMenuItem(
                        value: purity,
                        child: Text(purity),
                      );
                    }).toList(),
                    onChanged: (val) {
                      setDialogState(() => selectedPurity = val);
                    },
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Weight Input
              Text(
                'Weight (grams)',
                style: GoogleFonts.inter(
                  fontSize: 13,
                  color: Theme.of(
                    context,
                  ).colorScheme.onSurface.withOpacity(0.7),
                ),
              ),
              const SizedBox(height: 6),
              TextField(
                controller: weightController,
                keyboardType: TextInputType.number,
                decoration: InputDecoration(
                  hintText: 'e.g., 10',
                  suffixText: 'grams',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Cancel'),
            ),
            FilledButton(
              onPressed: () async {
                final weight = int.tryParse(weightController.text);
                if (selectedType != null &&
                    selectedPurity != null &&
                    weight != null &&
                    weight > 0) {
                  final option = GoldOption(
                    id: GoldOption.generateId(),
                    type: selectedType!,
                    purity: selectedPurity!,
                    weight: weight,
                  );
                  await SettingsService().addGoldOptionV2(option);
                  final updatedOptions = await SettingsService()
                      .getGoldOptionsV2();
                  setState(() {
                    _availableGoldOptions = updatedOptions;
                  });
                  if (mounted) Navigator.pop(context);
                }
              },
              child: const Text('Add'),
            ),
          ],
        ),
      ),
    );
  }

  /// Update total cost controllers based on selected options
  void _updateTotalCostControllers() {
    // Get selected gold option IDs
    final selectedOptionIds = _selectedGoldOptions.map((opt) => opt.id).toSet();

    // Remove controllers for options no longer selected
    _goldOptionTotalCostControllers.keys
        .where((id) => !selectedOptionIds.contains(id))
        .toList()
        .forEach((id) {
          _goldOptionTotalCostControllers[id]?.dispose();
          _goldOptionTotalCostControllers.remove(id);
        });

    // Remove reward state for options no longer selected
    _goldOptionRewardEnabled.keys
        .where((id) => !selectedOptionIds.contains(id))
        .toList()
        .forEach((id) {
          _goldOptionRewardControllers[id]?.dispose();
          _goldOptionRewardEnabled.remove(id);
          _goldOptionRewardType.remove(id);
          _goldOptionRewardControllers.remove(id);
        });

    // Add controllers for new gold options
    for (final option in _selectedGoldOptions) {
      // Total cost controller
      if (!_goldOptionTotalCostControllers.containsKey(option.id)) {
        _goldOptionTotalCostControllers[option.id] = TextEditingController(
          text: '',
        )..addListener(() => setState(() {}));
      }

      // Reward state - always enabled by default, fixed amount only
      if (!_goldOptionRewardEnabled.containsKey(option.id)) {
        _goldOptionRewardEnabled[option.id] = true; // Always enabled
        _goldOptionRewardType[option.id] = 'Fixed Amount'; // Only fixed amount
        _goldOptionRewardControllers[option.id] = TextEditingController(
          text: '0',
        )..addListener(() => setState(() {}));
      }
    }

    setState(() {});
  }

  /// Get total costs as a map
  Map<String, double> _getTotalCosts() {
    final costs = <String, double>{};
    for (var option in _selectedGoldOptions) {
      costs[option.id] =
          double.tryParse(
            _goldOptionTotalCostControllers[option.id]?.text ?? '0',
          ) ??
          0;
    }
    return costs;
  }

  /// Get gold option rewards as a map
  Map<String, Map<String, dynamic>> _getGoldOptionRewards() {
    final rewards = <String, Map<String, dynamic>>{};
    final totalCosts = _getTotalCosts();

    for (var option in _selectedGoldOptions) {
      // Always enabled, only fixed amount
      final value =
          double.tryParse(
            _goldOptionRewardControllers[option.id]?.text ?? '0',
          ) ??
          0;

      rewards[option.id] = {
        'enabled': true, // Always enabled
        'type': 'Fixed Amount', // Only fixed amount
        'value': value,
        'calculatedAmount': value,
        'totalCost': totalCosts[option.id] ?? 0,
      };
    }

    return rewards;
  }

  void _navigateToVerify() {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => VerifyChittiScreen(
          name: _nameController.text,
          duration: _duration,
          startMonth: _selectedStartMonth,
          goldOptions: List<GoldOption>.from(_selectedGoldOptions),
          totalCosts: _getTotalCosts(),
          maxSlots: int.tryParse(_maxSlotsController.text) ?? 70,
          paymentDay: _paymentDay,
          luckyDrawDay: _luckyDrawDay,
          goldOptionRewards: _getGoldOptionRewards(),
          nameAutoGenerated: _nameAutoGenerated,
          appSettings: _appSettings,
          isEditMode: isEditMode,
          chittiId: chittiId,
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final backgroundColor = Theme.of(context).scaffoldBackgroundColor;

    return Scaffold(
      backgroundColor: backgroundColor,
      body: SafeArea(
        child: Column(
          children: [
            // Header
            Container(
              height: 64,
              padding: const EdgeInsets.symmetric(horizontal: 16),
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.surface,
                border: Border(
                  bottom: BorderSide(
                    color: Theme.of(context).colorScheme.outline,
                  ),
                ),
              ),
              child: Row(
                children: [
                  InkWell(
                    onTap: () => Navigator.pop(context),
                    child: Icon(
                      Icons.arrow_back_ios_new,
                      size: 24,
                      color: Theme.of(context).colorScheme.onSurface,
                    ),
                  ),
                  Expanded(
                    child: Text(
                      isEditMode ? 'Edit Chitti' : 'Create New Chitti',
                      textAlign: TextAlign.center,
                      style: GoogleFonts.inter(
                        fontSize: 18,
                        fontWeight: FontWeight.w600,
                        color: Theme.of(context).colorScheme.onSurface,
                      ),
                    ),
                  ),
                  const SizedBox(width: 24),
                ],
              ),
            ),

            Expanded(
              child: ListView(
                padding: const EdgeInsets.all(16),
                children: [
                  // Basic Details Section
                  _buildSectionContainer(
                    context,
                    title: 'Basic Details',
                    children: [
                      _buildTextFieldLabel('Chitti Name'),
                      const SizedBox(height: 6),
                      Row(
                        children: [
                          Expanded(
                            child: _buildTextField(
                              context,
                              _nameController,
                              enabled: true,
                            ),
                          ),
                          const SizedBox(width: 8),
                          IconButton(
                            icon: Icon(
                              Icons.refresh,
                              size: 20,
                              color: Theme.of(context).colorScheme.primary,
                            ),
                            tooltip: 'Regenerate Name',
                            onPressed: _generateChittiName,
                            style: IconButton.styleFrom(
                              backgroundColor: Theme.of(
                                context,
                              ).colorScheme.primaryContainer,
                              padding: const EdgeInsets.all(12),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 16),
                      _buildTextFieldLabel('Duration'),
                      const SizedBox(height: 6),
                      _buildDurationStepper(context),
                      const SizedBox(height: 16),
                      _buildTextFieldLabel('Start Month'),
                      const SizedBox(height: 6),
                      _buildDropdown(context),
                      const SizedBox(height: 16),
                      // Timeline Preview
                      Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: Theme.of(
                            context,
                          ).colorScheme.primaryContainer.withOpacity(0.3),
                          borderRadius: BorderRadius.circular(8),
                          border: Border.all(
                            color: Theme.of(
                              context,
                            ).colorScheme.primary.withOpacity(0.3),
                          ),
                        ),
                        child: Row(
                          children: [
                            Icon(
                              Icons.timeline,
                              size: 20,
                              color: Theme.of(context).colorScheme.primary,
                            ),
                            const SizedBox(width: 12),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    'Chitti Timeline',
                                    style: GoogleFonts.inter(
                                      fontSize: 12,
                                      fontWeight: FontWeight.w500,
                                      color: Theme.of(
                                        context,
                                      ).colorScheme.onSurface.withOpacity(0.7),
                                    ),
                                  ),
                                  const SizedBox(height: 4),
                                  Text(
                                    '$_selectedStartMonth  →  ${_calculateEndMonth()}',
                                    style: GoogleFonts.inter(
                                      fontSize: 14,
                                      fontWeight: FontWeight.w600,
                                      color: Theme.of(
                                        context,
                                      ).colorScheme.primary,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            Container(
                              padding: const EdgeInsets.symmetric(
                                horizontal: 8,
                                vertical: 4,
                              ),
                              decoration: BoxDecoration(
                                color: Theme.of(context).colorScheme.primary,
                                borderRadius: BorderRadius.circular(12),
                              ),
                              child: Text(
                                '$_duration months',
                                style: GoogleFonts.inter(
                                  fontSize: 12,
                                  fontWeight: FontWeight.w600,
                                  color: Theme.of(
                                    context,
                                  ).colorScheme.onPrimary,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 24),

                  // Dates & Configuration Section
                  _buildSectionContainer(
                    context,
                    title: 'Dates & Configuration',
                    children: [
                      Row(
                        children: [
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                _buildTextFieldLabel('Payment Day'),
                                const SizedBox(height: 6),
                                _buildDayDropdown(
                                  context,
                                  _paymentDay,
                                  (val) => setState(() => _paymentDay = val),
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(width: 16),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                _buildTextFieldLabel('Lucky Draw Day'),
                                const SizedBox(height: 6),
                                _buildDayDropdown(
                                  context,
                                  _luckyDrawDay,
                                  (val) => setState(() => _luckyDrawDay = val),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),

                  // Gold Options Section
                  _buildSectionContainer(
                    context,
                    title: 'Gold Options',
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            'Select gold options',
                            style: GoogleFonts.inter(
                              fontSize: 14,
                              fontWeight: FontWeight.w500,
                              color: Theme.of(
                                context,
                              ).colorScheme.onSurface.withOpacity(0.8),
                            ),
                          ),
                          TextButton.icon(
                            onPressed: _showAddGoldOptionDialog,
                            icon: Icon(
                              Icons.add_circle_outline,
                              size: 18,
                              color: Theme.of(context).colorScheme.primary,
                            ),
                            label: Text(
                              'Add New',
                              style: GoogleFonts.inter(
                                fontSize: 13,
                                color: Theme.of(context).colorScheme.primary,
                              ),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 12),
                      if (_availableGoldOptions.isEmpty)
                        Container(
                          padding: const EdgeInsets.all(24),
                          decoration: BoxDecoration(
                            color: Theme.of(
                              context,
                            ).colorScheme.surfaceContainerHighest,
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: Center(
                            child: Text(
                              'No gold options available.\nGo to Settings > Masters to add options.',
                              textAlign: TextAlign.center,
                              style: GoogleFonts.inter(
                                color: Theme.of(
                                  context,
                                ).colorScheme.onSurface.withOpacity(0.6),
                              ),
                            ),
                          ),
                        )
                      else
                        Wrap(
                          spacing: 10,
                          runSpacing: 10,
                          children: _availableGoldOptions.map((option) {
                            return _buildGoldOptionCard(context, option);
                          }).toList(),
                        ),

                      // Gold Option Configuration (Total Cost + Reward)
                      if (_selectedGoldOptions.isNotEmpty) ...[
                        const SizedBox(height: 20),
                        Divider(color: Theme.of(context).colorScheme.outline),
                        const SizedBox(height: 12),
                        Text(
                          'Gold Option Configuration',
                          style: GoogleFonts.inter(
                            fontSize: 14,
                            fontWeight: FontWeight.w600,
                            color: Theme.of(context).colorScheme.onSurface,
                          ),
                        ),
                        const SizedBox(height: 12),
                        ..._selectedGoldOptions.map((option) {
                          return _buildRewardConfigForOption(context, option);
                        }),
                      ],
                    ],
                  ),
                  const SizedBox(height: 24),

                  // EMI Preview Table
                  if (_selectedGoldOptions.isNotEmpty)
                    _buildSectionContainer(
                      context,
                      title: 'EMI Preview Table',
                      children: [
                        Container(
                          decoration: BoxDecoration(
                            border: Border.all(
                              color: Theme.of(context).colorScheme.outline,
                            ),
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: Column(
                            children: [
                              _buildTableHeaderV2(context),
                              ..._selectedGoldOptions.asMap().entries.map((
                                entry,
                              ) {
                                final option = entry.value;
                                final totalValue =
                                    double.tryParse(
                                      _goldOptionTotalCostControllers[option.id]
                                              ?.text ??
                                          '0',
                                    ) ??
                                    0;
                                final emiBreakdown =
                                    CurrencyUtils.getEMIBreakdown(
                                      totalValue,
                                      _duration,
                                    );
                                final regularEMI =
                                    emiBreakdown['regularMonths'] as double;
                                final firstMonthEMI =
                                    emiBreakdown['firstMonth'] as double;
                                final hasRemainder =
                                    emiBreakdown['hasRemainder'] as bool;

                                final currency = SettingsService()
                                    .getCurrencySymbol();
                                final isLast =
                                    entry.key ==
                                    _selectedGoldOptions.length - 1;

                                return _buildTableRowV2(
                                  context,
                                  option,
                                  '$currency${totalValue.toStringAsFixed(0)}',
                                  '$currency${regularEMI.toStringAsFixed(0)}${hasRemainder ? ' (+${(firstMonthEMI - regularEMI).toStringAsFixed(0)})' : ''}',
                                  isLast: isLast,
                                );
                              }),
                            ],
                          ),
                        ),
                      ],
                    ),
                  const SizedBox(height: 24),

                  // Slots Section
                  _buildSectionContainer(
                    context,
                    title: 'Slots',
                    children: [
                      _buildTextFieldLabel('Max Slots'),
                      const SizedBox(height: 6),
                      _buildTextField(
                        context,
                        _maxSlotsController,
                        isNumber: true,
                        enabled: true,
                      ),
                    ],
                  ),
                  const SizedBox(height: 80),
                ],
              ),
            ),

            // Footer
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.surface,
                border: Border(
                  top: BorderSide(color: Theme.of(context).colorScheme.outline),
                ),
              ),
              child: SizedBox(
                width: double.infinity,
                height: 48,
                child: ElevatedButton(
                  onPressed: _selectedGoldOptions.isEmpty
                      ? null
                      : _navigateToVerify,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Theme.of(context).colorScheme.tertiary,
                    foregroundColor: Theme.of(context).colorScheme.surface,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                    elevation: 0,
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text(
                        isEditMode ? 'Review & Update' : 'Review & Confirm',
                        style: GoogleFonts.inter(
                          fontSize: 16,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      const SizedBox(width: 8),
                      const Icon(Icons.arrow_forward, size: 20),
                    ],
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  /// Builds a duration stepper with increment/decrement buttons
  Widget _buildDurationStepper(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
      decoration: BoxDecoration(
        color: colorScheme.surface,
        border: Border.all(color: colorScheme.outline),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        children: [
          // Decrement Button
          _buildStepperButton(
            context,
            icon: Icons.remove,
            onPressed: _duration > _minDuration
                ? () {
                    setState(() => _duration--);
                    _generateChittiName();
                  }
                : null,
          ),

          // Duration Display
          Expanded(
            child: Column(
              children: [
                Text(
                  '$_duration',
                  style: GoogleFonts.inter(
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                    color: colorScheme.onSurface,
                  ),
                ),
                Text(
                  'Months',
                  style: GoogleFonts.inter(
                    fontSize: 12,
                    color: colorScheme.onSurfaceVariant,
                  ),
                ),
              ],
            ),
          ),

          // Increment Button
          _buildStepperButton(
            context,
            icon: Icons.add,
            onPressed: _duration < _maxDuration
                ? () {
                    setState(() => _duration++);
                    _generateChittiName();
                  }
                : null,
          ),
        ],
      ),
    );
  }

  /// Builds individual stepper button
  Widget _buildStepperButton(
    BuildContext context, {
    required IconData icon,
    VoidCallback? onPressed,
  }) {
    final colorScheme = Theme.of(context).colorScheme;
    final isEnabled = onPressed != null;

    return Material(
      color: isEnabled
          ? colorScheme.primary
          : colorScheme.surfaceContainerHighest,
      borderRadius: BorderRadius.circular(16),
      child: InkWell(
        onTap: onPressed,
        borderRadius: BorderRadius.circular(16),
        child: Container(
          width: 56,
          height: 56,
          alignment: Alignment.center,
          child: Icon(
            icon,
            size: 24,
            color: isEnabled
                ? colorScheme.onPrimary
                : colorScheme.onSurfaceVariant,
          ),
        ),
      ),
    );
  }

  Widget _buildSectionContainer(
    BuildContext context, {
    required String title,
    required List<Widget> children,
    Widget? trailing,
  }) {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Theme.of(context).colorScheme.surface,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(
          color: Theme.of(context).colorScheme.outline.withOpacity(0.1),
        ),
        boxShadow: [
          BoxShadow(
            color: Theme.of(context).colorScheme.onSurface.withOpacity(0.03),
            offset: const Offset(0, 4),
            blurRadius: 12,
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                title,
                style: GoogleFonts.inter(
                  fontSize: 16,
                  fontWeight: FontWeight.w700,
                  color: Theme.of(context).colorScheme.onSurface,
                  letterSpacing: -0.5,
                ),
              ),
              if (trailing != null) trailing,
            ],
          ),
          const SizedBox(height: 20),
          ...children,
        ],
      ),
    );
  }

  Widget _buildTextFieldLabel(String text) {
    return Padding(
      padding: const EdgeInsets.only(left: 4, bottom: 8),
      child: Text(
        text,
        style: GoogleFonts.inter(
          fontSize: 13,
          fontWeight: FontWeight.w600,
          color: Theme.of(context).colorScheme.onSurface.withOpacity(0.6),
          letterSpacing: 0.2,
        ),
      ),
    );
  }

  Widget _buildTextField(
    BuildContext context,
    TextEditingController controller, {
    bool enabled = true,
    bool isNumber = false,
    String? hint,
    Widget? suffix,
  }) {
    final colorScheme = Theme.of(context).colorScheme;

    return Container(
      decoration: BoxDecoration(
        color: enabled
            ? colorScheme.surface
            : colorScheme.surfaceContainerHighest.withOpacity(0.3),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: enabled
              ? colorScheme.outline.withOpacity(0.2)
              : colorScheme.outline.withOpacity(0.1),
        ),
      ),
      child: TextField(
        enabled: enabled,
        controller: controller,
        keyboardType: isNumber ? TextInputType.number : TextInputType.text,
        style: GoogleFonts.inter(
          fontSize: 15,
          fontWeight: FontWeight.w500,
          color: enabled
              ? colorScheme.onSurface
              : colorScheme.onSurface.withOpacity(0.5),
        ),
        decoration: InputDecoration(
          hintText: hint,
          hintStyle: GoogleFonts.inter(
            color: colorScheme.onSurface.withOpacity(0.3),
            fontSize: 15,
          ),
          border: InputBorder.none,
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 16,
            vertical: 16,
          ),
          suffixIcon: suffix,
          isDense: true,
        ),
      ),
    );
  }

  Widget _buildDropdown(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    return GestureDetector(
      onTap: () => _showMonthPicker(context),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
        decoration: BoxDecoration(
          color: colorScheme.surface,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(color: colorScheme.outline.withOpacity(0.2)),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text(
              _selectedStartMonth,
              style: GoogleFonts.inter(
                fontSize: 15,
                fontWeight: FontWeight.w500,
                color: colorScheme.onSurface,
              ),
            ),
            Icon(
              Icons.calendar_month_outlined,
              size: 20,
              color: colorScheme.primary,
            ),
          ],
        ),
      ),
    );
  }

  /// Build a selectable gold option card
  Widget _buildGoldOptionCard(BuildContext context, GoldOption option) {
    bool isSelected = _selectedGoldOptions.any((o) => o.id == option.id);
    final colorScheme = Theme.of(context).colorScheme;

    return InkWell(
      onTap: () {
        setState(() {
          if (isSelected) {
            _selectedGoldOptions.removeWhere((o) => o.id == option.id);
          } else {
            _selectedGoldOptions.add(option);
          }
        });
        _updateTotalCostControllers();
      },
      borderRadius: BorderRadius.circular(20),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        width: 110,
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 16),
        decoration: BoxDecoration(
          color: isSelected ? colorScheme.primary : colorScheme.surface,
          borderRadius: BorderRadius.circular(20),
          border: Border.all(
            width: 1.5,
            color: isSelected
                ? colorScheme.primary
                : colorScheme.outline.withOpacity(0.1),
          ),
          boxShadow: isSelected
              ? [
                  BoxShadow(
                    color: colorScheme.primary.withOpacity(0.3),
                    blurRadius: 12,
                    offset: const Offset(0, 4),
                  ),
                ]
              : [
                  BoxShadow(
                    color: colorScheme.onSurface.withOpacity(0.03),
                    blurRadius: 8,
                    offset: const Offset(0, 2),
                  ),
                ],
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // Type Icon
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: isSelected
                    ? Colors.white.withOpacity(0.2)
                    : colorScheme.surfaceContainerHighest.withOpacity(0.5),
                shape: BoxShape.circle,
              ),
              child: Text(
                option.typeIcon,
                style: const TextStyle(fontSize: 20),
              ),
            ),
            const SizedBox(height: 12),
            // Weight
            Text(
              '${option.weight}g',
              style: GoogleFonts.inter(
                fontSize: 18,
                fontWeight: FontWeight.w800,
                color: isSelected ? Colors.white : colorScheme.onSurface,
                letterSpacing: -0.5,
              ),
            ),
            const SizedBox(height: 4),
            // Type
            Text(
              option.type,
              style: GoogleFonts.inter(
                fontSize: 12,
                fontWeight: FontWeight.w500,
                color: isSelected
                    ? Colors.white70
                    : colorScheme.onSurface.withOpacity(0.6),
              ),
            ),
            const SizedBox(height: 8),
            // Purity Badge
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
              decoration: BoxDecoration(
                color: isSelected
                    ? Colors.white.withOpacity(0.15)
                    : colorScheme.surfaceContainerHighest,
                borderRadius: BorderRadius.circular(8),
              ),
              child: Text(
                option.purity,
                style: GoogleFonts.inter(
                  fontSize: 10,
                  fontWeight: FontWeight.w600,
                  color: isSelected
                      ? Colors.white
                      : colorScheme.onSurface.withOpacity(0.8),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTableHeaderV2(BuildContext context) {
    return Container(
      color: Theme.of(context).colorScheme.surfaceContainer,
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      child: Row(
        children: [
          Expanded(
            flex: 2,
            child: Text(
              'Option',
              style: GoogleFonts.inter(
                fontSize: 12,
                fontWeight: FontWeight.w600,
                color: Theme.of(context).colorScheme.onSurface,
              ),
            ),
          ),
          Expanded(
            child: Text(
              'Total',
              style: GoogleFonts.inter(
                fontSize: 12,
                fontWeight: FontWeight.w600,
                color: Theme.of(context).colorScheme.onSurface,
              ),
              textAlign: TextAlign.center,
            ),
          ),
          Expanded(
            child: Text(
              'Monthly EMI',
              style: GoogleFonts.inter(
                fontSize: 12,
                fontWeight: FontWeight.w600,
                color: Theme.of(context).colorScheme.onSurface,
              ),
              textAlign: TextAlign.end,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildTableRowV2(
    BuildContext context,
    GoldOption option,
    String total,
    String monthly, {
    bool isLast = false,
  }) {
    return Container(
      decoration: isLast
          ? null
          : BoxDecoration(
              border: Border(
                bottom: BorderSide(
                  color: Theme.of(context).colorScheme.outline,
                ),
              ),
            ),
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      child: Row(
        children: [
          Expanded(
            flex: 2,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  '${option.typeIcon} ${option.weight}g ${option.type}',
                  style: GoogleFonts.inter(
                    fontSize: 14,
                    fontWeight: FontWeight.w500,
                    color: Theme.of(context).colorScheme.onSurface,
                  ),
                ),
                Text(
                  option.purity,
                  style: GoogleFonts.inter(
                    fontSize: 11,
                    color: Theme.of(
                      context,
                    ).colorScheme.onSurface.withOpacity(0.6),
                  ),
                ),
              ],
            ),
          ),
          Expanded(
            child: Text(
              total,
              style: GoogleFonts.inter(
                fontSize: 14,
                color: Theme.of(context).colorScheme.onSurface,
              ),
              textAlign: TextAlign.center,
            ),
          ),
          Expanded(
            child: Text(
              monthly,
              style: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: Theme.of(context).colorScheme.primary,
              ),
              textAlign: TextAlign.end,
            ),
          ),
        ],
      ),
    );
  }

  // Keep legacy methods for backward compatibility
  Widget _buildGoldOptionCheckbox(
    BuildContext context,
    String id,
    String label,
  ) {
    // Legacy method - not used in new implementation
    return const SizedBox.shrink();
  }

  Widget _buildTableHeader(BuildContext context) {
    return Container(
      color: Theme.of(context).colorScheme.surfaceContainer,
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      child: Row(
        children: [
          Expanded(
            child: Text(
              'Gold Option',
              style: GoogleFonts.inter(
                fontSize: 12,
                fontWeight: FontWeight.w600,
                color: Theme.of(context).colorScheme.onSurface,
              ),
            ),
          ),
          Expanded(
            child: Text(
              'Total Value',
              style: GoogleFonts.inter(
                fontSize: 12,
                fontWeight: FontWeight.w600,
                color: Theme.of(context).colorScheme.onSurface,
              ),
            ),
          ),
          Expanded(
            child: Text(
              'Monthly EMI',
              style: GoogleFonts.inter(
                fontSize: 12,
                fontWeight: FontWeight.w600,
                color: Theme.of(context).colorScheme.onSurface,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildTableRow(
    BuildContext context,
    String gold,
    String total,
    String monthly, {
    bool isLast = false,
  }) {
    return Container(
      decoration: isLast
          ? null
          : BoxDecoration(
              border: Border(
                bottom: BorderSide(
                  color: Theme.of(context).colorScheme.outline,
                ),
              ),
            ),
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      child: Row(
        children: [
          Expanded(
            child: Text(
              gold,
              style: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w500,
                color: Theme.of(context).colorScheme.onSurface,
              ),
            ),
          ),
          Expanded(
            child: Text(
              total,
              style: GoogleFonts.inter(
                fontSize: 14,
                color: Theme.of(context).colorScheme.onSurface,
              ),
            ),
          ),
          Expanded(
            child: Text(
              monthly,
              style: GoogleFonts.inter(
                fontSize: 14,
                color: Theme.of(context).colorScheme.onSurface,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildDayDropdown(
    BuildContext context,
    String currentValue,
    Function(String) onChanged,
  ) {
    final days = List.generate(28, (index) => (index + 1).toString());
    final colorScheme = Theme.of(context).colorScheme;

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      decoration: BoxDecoration(
        color: colorScheme.surface,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: colorScheme.outline.withOpacity(0.2)),
      ),
      child: DropdownButtonHideUnderline(
        child: DropdownButton<String>(
          value: currentValue,
          isExpanded: true,
          dropdownColor: colorScheme.surface,
          icon: Icon(Icons.expand_more_rounded, color: colorScheme.primary),
          items: days.map((String value) {
            return DropdownMenuItem<String>(
              value: value,
              child: Text(
                'Day $value',
                style: GoogleFonts.inter(
                  fontSize: 15,
                  fontWeight: FontWeight.w500,
                  color: colorScheme.onSurface,
                ),
              ),
            );
          }).toList(),
          onChanged: (val) {
            if (val != null) onChanged(val);
          },
        ),
      ),
    );
  }

  Widget _buildRewardConfigForOption(BuildContext context, GoldOption option) {
    // Safely get or create controllers for this option
    if (!_goldOptionTotalCostControllers.containsKey(option.id)) {
      _goldOptionTotalCostControllers[option.id] = TextEditingController(
        text: '',
      )..addListener(() => setState(() {}));
    }
    if (!_goldOptionRewardControllers.containsKey(option.id)) {
      _goldOptionRewardControllers[option.id] = TextEditingController(text: '0')
        ..addListener(() => setState(() {}));
      _goldOptionRewardEnabled[option.id] = true; // Always enabled
      _goldOptionRewardType[option.id] = 'Fixed Amount'; // Only fixed amount
    }

    final colorScheme = Theme.of(context).colorScheme;
    final totalCostController = _goldOptionTotalCostControllers[option.id]!;
    final rewardController = _goldOptionRewardControllers[option.id]!;

    // Calculate EMI preview with remainder handling
    final totalCost = double.tryParse(totalCostController.text) ?? 0;
    final emiBreakdown = CurrencyUtils.getEMIBreakdown(totalCost, _duration);
    final firstMonthEMI = emiBreakdown['firstMonth'] as double;
    final regularEMI = emiBreakdown['regularMonths'] as double;
    final emiRemainder = emiBreakdown['remainder'] as double;
    final hasRemainder = emiBreakdown['hasRemainder'] as bool;
    final currency = SettingsService().getCurrencySymbol();

    // Reward amount IS the monthly discount (direct value, not divided)
    final monthlyDiscount = double.tryParse(rewardController.text) ?? 0;

    return Container(
      margin: const EdgeInsets.only(bottom: 20),
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: colorScheme.surface,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: colorScheme.primary.withOpacity(0.1)),
        boxShadow: [
          BoxShadow(
            color: colorScheme.primary.withOpacity(0.02),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header with gold option label
          Text(
            option.displayLabel,
            style: GoogleFonts.inter(
              fontSize: 14,
              fontWeight: FontWeight.w600,
              color: Theme.of(context).colorScheme.onSurface,
            ),
          ),
          const SizedBox(height: 12),

          // Total Cost Input
          Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildTextFieldLabel('Total Cost ($currency)'),
                    const SizedBox(height: 6),
                    _buildTextField(
                      context,
                      totalCostController,
                      isNumber: true,
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 12),
              // Reward Amount Input
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    _buildTextFieldLabel('Monthly Discount ($currency)'),
                    const SizedBox(height: 6),
                    _buildTextField(context, rewardController, isNumber: true),
                  ],
                ),
              ),
            ],
          ),

          // EMI and Discount Preview
          if (totalCost > 0 || monthlyDiscount > 0) ...[
            const SizedBox(height: 12),
            Container(
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.surfaceContainerHighest,
                borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                children: [
                  // Monthly EMI
                  if (totalCost > 0)
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Monthly EMI',
                            style: GoogleFonts.inter(
                              fontSize: 11,
                              color: Theme.of(
                                context,
                              ).colorScheme.onSurfaceVariant,
                            ),
                          ),
                          const SizedBox(height: 2),
                          Text(
                            '$currency${regularEMI.toStringAsFixed(0)}',
                            style: GoogleFonts.inter(
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                              color: Theme.of(context).colorScheme.primary,
                            ),
                          ),
                          if (hasRemainder)
                            Text(
                              '1st: $currency${firstMonthEMI.toStringAsFixed(0)} (+$currency${emiRemainder.toStringAsFixed(0)})',
                              style: GoogleFonts.inter(
                                fontSize: 10,
                                color: Colors.green.shade700,
                              ),
                            ),
                        ],
                      ),
                    ),
                  // Monthly Discount
                  if (monthlyDiscount > 0)
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Monthly Discount',
                            style: GoogleFonts.inter(
                              fontSize: 11,
                              color: Theme.of(
                                context,
                              ).colorScheme.onSurfaceVariant,
                            ),
                          ),
                          const SizedBox(height: 2),
                          Text(
                            '-$currency${monthlyDiscount.toStringAsFixed(0)}/mo',
                            style: GoogleFonts.inter(
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                              color: Colors.green.shade700,
                            ),
                          ),
                        ],
                      ),
                    ),
                  // EMI After Discount
                  if (totalCost > 0 && monthlyDiscount > 0)
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'After Win',
                            style: GoogleFonts.inter(
                              fontSize: 11,
                              color: Theme.of(
                                context,
                              ).colorScheme.onSurfaceVariant,
                            ),
                          ),
                          const SizedBox(height: 2),
                          Text(
                            '$currency${(regularEMI - monthlyDiscount).toStringAsFixed(0)}/mo',
                            style: GoogleFonts.inter(
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                              color: Theme.of(context).colorScheme.tertiary,
                            ),
                          ),
                        ],
                      ),
                    ),
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }

  void _showMonthPicker(BuildContext context) {
    int displayYear = DateTime.now().year;
    final int minYear = 2020; // Allow selecting dates from 2020 onwards
    final int maxYear = DateTime.now().year + 10;

    final months = [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ];

    // Helper to get full month name
    final fullMonthNames = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];

    showModalBottomSheet(
      context: context,
      backgroundColor: Theme.of(context).cardColor,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (BuildContext context) {
        return StatefulBuilder(
          builder: (BuildContext context, StateSetter setModalState) {
            return Container(
              padding: const EdgeInsets.all(16),
              height: 320,
              child: Column(
                children: [
                  // Year Selector
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      IconButton(
                        onPressed: displayYear > minYear
                            ? () => setModalState(() => displayYear--)
                            : null,
                        icon: Icon(
                          Icons.chevron_left,
                          color: displayYear > minYear ? null : Colors.grey,
                        ),
                      ),
                      Text(
                        displayYear.toString(),
                        style: GoogleFonts.inter(
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      IconButton(
                        onPressed: displayYear < maxYear
                            ? () => setModalState(() => displayYear++)
                            : null,
                        icon: Icon(
                          Icons.chevron_right,
                          color: displayYear < maxYear ? null : Colors.grey,
                        ),
                      ),
                    ],
                  ),
                  const Divider(),
                  const SizedBox(height: 8),
                  // Month Grid
                  Expanded(
                    child: GridView.builder(
                      gridDelegate:
                          const SliverGridDelegateWithFixedCrossAxisCount(
                            crossAxisCount: 4,
                            childAspectRatio: 1.5,
                            crossAxisSpacing: 12,
                            mainAxisSpacing: 12,
                          ),
                      itemCount: 12,
                      itemBuilder: (context, index) {
                        // Allow selecting any month in any year within the minYear-maxYear range
                        // const isSelected = ... (optional logic if we want to highlight current selection)

                        return InkWell(
                          onTap: () {
                            setState(() {
                              _selectedStartMonth =
                                  '${fullMonthNames[index]} $displayYear';
                            });
                            _generateChittiName();
                            Navigator.pop(context);
                          },
                          child: Container(
                            alignment: Alignment.center,
                            decoration: BoxDecoration(
                              color: Theme.of(
                                context,
                              ).colorScheme.primaryContainer.withOpacity(0.3),
                              borderRadius: BorderRadius.circular(8),
                              border: Border.all(
                                color: Theme.of(
                                  context,
                                ).colorScheme.primary.withOpacity(0.3),
                              ),
                            ),
                            child: Text(
                              months[index],
                              style: GoogleFonts.inter(
                                color: Theme.of(context).colorScheme.onSurface,
                                fontWeight: FontWeight.w500,
                              ),
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                ],
              ),
            );
          },
        );
      },
    );
  }
}
