import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:chitt/services/chitti_service.dart';
import 'package:chitt/services/settings_service.dart';
import 'package:chitt/core/models/gold_option.dart';
import 'package:chitt/utils/currency_utils.dart';

class VerifyChittiScreen extends StatefulWidget {
  final String name;
  final int duration;
  final String startMonth;
  final List<GoldOption> goldOptions;
  final Map<String, double> totalCosts; // Option ID -> Total cost
  final int maxSlots;
  final String paymentDay;
  final String luckyDrawDay;
  final Map<String, Map<String, dynamic>> goldOptionRewards;
  final bool nameAutoGenerated;
  final Map<String, dynamic>? appSettings;
  final bool isEditMode;
  final String? chittiId;

  const VerifyChittiScreen({
    super.key,
    required this.name,
    required this.duration,
    required this.startMonth,
    required this.goldOptions,
    required this.totalCosts,
    required this.maxSlots,
    required this.paymentDay,
    required this.luckyDrawDay,
    required this.goldOptionRewards,
    required this.nameAutoGenerated,
    this.appSettings,
    this.isEditMode = false,
    this.chittiId,
  });

  @override
  State<VerifyChittiScreen> createState() => _VerifyChittiScreenState();
}

class _VerifyChittiScreenState extends State<VerifyChittiScreen> {
  bool _isLoading = false;
  late String _selectedOptionIdForSchedule;

  @override
  void initState() {
    super.initState();
    // Initialize with the first available option
    _selectedOptionIdForSchedule = widget.goldOptions.isNotEmpty
        ? widget.goldOptions.first.id
        : '';
  }

  String _calculateEndMonth() {
    final parts = widget.startMonth.split(' ');
    if (parts.length != 2) return widget.startMonth;

    const months = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];
    final monthIndex = months.indexOf(parts[0]);
    final year = int.tryParse(parts[1]) ?? DateTime.now().year;

    if (monthIndex == -1) return widget.startMonth;

    final endMonthIndex = (monthIndex + widget.duration - 1) % 12;
    final endYear = year + ((monthIndex + widget.duration - 1) ~/ 12);

    return '${months[endMonthIndex]} $endYear';
  }

  Future<void> _handleSubmit() async {
    setState(() => _isLoading = true);

    // Build gold options for storage (legacy format for compatibility)
    final goldOptionsData = <Map<String, dynamic>>[];
    for (final option in widget.goldOptions) {
      final totalValue = widget.totalCosts[option.id] ?? 0;
      final emiBreakdown = CurrencyUtils.getEMIBreakdown(
        totalValue,
        widget.duration,
      );
      goldOptionsData.add({
        'weight': '${option.weight}g',
        'grams': option.weight,
        'total_value': totalValue,
        'rate_per_gram': 0, // No longer used
        'price': (emiBreakdown['regularMonths'] as double)
            .round(), // Base EMI for display
        'firstMonthEMI': (emiBreakdown['firstMonth'] as double)
            .round(), // First month with remainder
        'emiRemainder': (emiBreakdown['remainder'] as double)
            .round(), // Remainder added to first month
        'type': option.type,
        'purity': option.purity,
      });
    }

    final chittiData = {
      'name': widget.name,
      'duration': widget.duration,
      'startMonth': widget.startMonth,
      'goldOptions': goldOptionsData,
      'goldOptionsV2': widget.goldOptions.map((o) => o.toMap()).toList(),
      'totalCosts': widget.totalCosts,
      'maxSlots': widget.maxSlots,
      'paymentDay': int.tryParse(widget.paymentDay) ?? 5,
      'luckyDrawDay': int.tryParse(widget.luckyDrawDay) ?? 10,
      'goldOptionRewards': widget.goldOptionRewards,
      'rewardConfig': null, // Clear legacy field
    };

    try {
      if (widget.isEditMode && widget.chittiId != null) {
        await ChittiService().updateChitti(widget.chittiId!, chittiData);
      } else {
        await ChittiService().createChitti(
          name: widget.name,
          duration: widget.duration,
          startMonth: widget.startMonth,
          goldOptions: goldOptionsData,
          maxSlots: widget.maxSlots,
          paymentDay: int.tryParse(widget.paymentDay) ?? 5,
          luckyDrawDay: int.tryParse(widget.luckyDrawDay) ?? 10,
          goldOptionRewards: widget.goldOptionRewards,
        );

        if (widget.nameAutoGenerated && widget.appSettings != null) {
          final newCounter = (widget.appSettings!['lastChittiNumber'] ?? 0) + 1;
          await SettingsService().updateAppSettings({
            'lastChittiNumber': newCounter,
          });
        }
      }

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              widget.isEditMode
                  ? 'Chitti updated successfully!'
                  : 'Chitti created successfully!',
            ),
            backgroundColor: Colors.green,
          ),
        );
        Navigator.of(context).popUntil((route) => route.isFirst);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e'), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final currency = SettingsService().getCurrencySymbol();
    final endMonth = _calculateEndMonth();

    return Scaffold(
      backgroundColor: Theme.of(context).scaffoldBackgroundColor,
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.surface,
        elevation: 0,
        scrolledUnderElevation: 0,
        leading: IconButton(
          icon: Icon(
            Icons.arrow_back_ios_new,
            size: 20,
            color: Theme.of(context).colorScheme.onSurface,
          ),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text(
          'Verify Details',
          style: GoogleFonts.inter(
            fontSize: 18,
            fontWeight: FontWeight.w700,
            color: Theme.of(context).colorScheme.onSurface,
            letterSpacing: -0.5,
          ),
        ),
        centerTitle: true,
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(1),
          child: Container(
            color: Theme.of(context).colorScheme.outline.withOpacity(0.1),
            height: 1,
          ),
        ),
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Header Banner
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(24),
                    decoration: BoxDecoration(
                      gradient: LinearGradient(
                        begin: Alignment.topLeft,
                        end: Alignment.bottomRight,
                        colors: [
                          Theme.of(context).colorScheme.primary,
                          Theme.of(context).colorScheme.tertiary,
                        ],
                      ),
                      borderRadius: BorderRadius.circular(24),
                      boxShadow: [
                        BoxShadow(
                          color: Theme.of(
                            context,
                          ).colorScheme.primary.withOpacity(0.3),
                          blurRadius: 15,
                          offset: const Offset(0, 8),
                        ),
                      ],
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Container(
                          padding: const EdgeInsets.all(10),
                          decoration: BoxDecoration(
                            color: Colors.white.withOpacity(0.2),
                            shape: BoxShape.circle,
                          ),
                          child: const Icon(
                            Icons.verified_rounded,
                            color: Colors.white,
                            size: 24,
                          ),
                        ),
                        const SizedBox(height: 16),
                        Text(
                          widget.isEditMode
                              ? 'Review & Update'
                              : 'Great Choice!',
                          style: GoogleFonts.inter(
                            fontSize: 22,
                            fontWeight: FontWeight.w800,
                            color: Colors.white,
                            letterSpacing: -0.5,
                          ),
                        ),
                        const SizedBox(height: 6),
                        Text(
                          widget.isEditMode
                              ? 'Please verify all details before updating the chitti.'
                              : 'Please verify all details before creating your new chitti.',
                          style: GoogleFonts.inter(
                            fontSize: 14,
                            fontWeight: FontWeight.w500,
                            color: Colors.white.withOpacity(0.8),
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 20),

                  // Basic Info Section
                  _buildSection(
                    context,
                    title: 'Basic Information',
                    icon: Icons.info_outline,
                    children: [
                      _buildInfoRow(context, 'Name', widget.name),
                      _buildInfoRow(
                        context,
                        'Duration',
                        '${widget.duration} months',
                      ),
                      _buildInfoRow(context, 'Start Month', widget.startMonth),
                      _buildInfoRow(context, 'End Month', endMonth),
                    ],
                  ),
                  const SizedBox(height: 16),

                  // Schedule Section
                  _buildSection(
                    context,
                    title: 'Schedule',
                    icon: Icons.calendar_today_outlined,
                    children: [
                      _buildInfoRow(
                        context,
                        'Payment Day',
                        'Day ${widget.paymentDay} of each month',
                      ),
                      _buildInfoRow(
                        context,
                        'Lucky Draw Day',
                        'Day ${widget.luckyDrawDay} of each month',
                      ),
                      _buildInfoRow(
                        context,
                        'Max Slots',
                        widget.maxSlots.toString(),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),

                  // Reward Section (per gold option)
                  if (widget.goldOptionRewards.values.any(
                    (r) => r['enabled'] == true,
                  ))
                    Column(
                      children: [
                        _buildSection(
                          context,
                          title: 'Winner Rewards',
                          icon: Icons.card_giftcard_outlined,
                          children: [
                            ...widget.goldOptions.map((option) {
                              final reward =
                                  widget.goldOptionRewards[option.id];
                              if (reward == null || reward['enabled'] != true) {
                                return const SizedBox.shrink();
                              }

                              final type = reward['type'] as String;
                              final value = reward['value'] as double;
                              final calculatedAmount =
                                  reward['calculatedAmount'] as double;

                              return Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  if (widget.goldOptions.indexOf(option) > 0)
                                    Padding(
                                      padding: const EdgeInsets.symmetric(
                                        vertical: 8,
                                      ),
                                      child: Divider(
                                        color: Theme.of(
                                          context,
                                        ).colorScheme.outline,
                                      ),
                                    ),
                                  Text(
                                    option.displayLabel,
                                    style: GoogleFonts.inter(
                                      fontSize: 13,
                                      fontWeight: FontWeight.w600,
                                      color: Theme.of(
                                        context,
                                      ).colorScheme.primary,
                                    ),
                                  ),
                                  const SizedBox(height: 6),
                                  _buildInfoRow(context, 'Type', type),
                                  _buildInfoRow(
                                    context,
                                    'Value',
                                    type == 'Percentage'
                                        ? '${value.toStringAsFixed(1)}% ($currency${calculatedAmount.toStringAsFixed(0)})'
                                        : '$currency${value.toStringAsFixed(0)}',
                                  ),
                                ],
                              );
                            }),
                          ],
                        ),
                        const SizedBox(height: 16),
                      ],
                    ),

                  // EMI Breakdown Section
                  _buildSection(
                    context,
                    title: 'EMI Breakdown',
                    icon: Icons.payments_outlined,
                    children: [
                      Container(
                        decoration: BoxDecoration(
                          color: Theme.of(context).colorScheme.surface,
                          borderRadius: BorderRadius.circular(16),
                          border: Border.all(
                            color: Theme.of(
                              context,
                            ).colorScheme.outline.withOpacity(0.1),
                          ),
                        ),
                        child: Column(
                          children: [
                            // Table Header
                            Container(
                              padding: const EdgeInsets.all(16),
                              decoration: BoxDecoration(
                                color: Theme.of(
                                  context,
                                ).colorScheme.primary.withOpacity(0.05),
                                borderRadius: const BorderRadius.vertical(
                                  top: Radius.circular(16),
                                ),
                              ),
                              child: Row(
                                children: [
                                  Expanded(
                                    flex: 2,
                                    child: Text(
                                      'Option',
                                      style: _headerStyle(context),
                                    ),
                                  ),
                                  Expanded(
                                    child: Text(
                                      'Total',
                                      style: _headerStyle(context),
                                      textAlign: TextAlign.center,
                                    ),
                                  ),
                                  Expanded(
                                    child: Text(
                                      'Monthly EMI',
                                      style: _headerStyle(context),
                                      textAlign: TextAlign.end,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            // Table Rows
                            ...widget.goldOptions.asMap().entries.map((entry) {
                              final option = entry.value;
                              final isLast =
                                  entry.key == widget.goldOptions.length - 1;
                              final totalValue =
                                  widget.totalCosts[option.id] ?? 0;
                              final emiBreakdown =
                                  CurrencyUtils.getEMIBreakdown(
                                    totalValue,
                                    widget.duration,
                                  );
                              final firstMonthEMI =
                                  emiBreakdown['firstMonth'] as double;
                              final regularEMI =
                                  emiBreakdown['regularMonths'] as double;
                              final hasRemainder =
                                  emiBreakdown['hasRemainder'] as bool;

                              return Container(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 16,
                                  vertical: 12,
                                ),
                                decoration: BoxDecoration(
                                  border: isLast
                                      ? null
                                      : Border(
                                          bottom: BorderSide(
                                            color: Theme.of(
                                              context,
                                            ).colorScheme.outline,
                                          ),
                                        ),
                                ),
                                child: Row(
                                  children: [
                                    Expanded(
                                      flex: 2,
                                      child: Column(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            '${option.typeIcon} ${option.weight}g ${option.type}',
                                            style: _cellStyle(context),
                                          ),
                                          Text(
                                            option.purity,
                                            style: _cellStyle(context).copyWith(
                                              fontSize: 11,
                                              color: Theme.of(context)
                                                  .colorScheme
                                                  .onSurface
                                                  .withValues(alpha: 0.6),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    Expanded(
                                      child: Text(
                                        '$currency${totalValue.toStringAsFixed(0)}',
                                        style: _cellStyle(context),
                                        textAlign: TextAlign.center,
                                      ),
                                    ),
                                    Expanded(
                                      child: Column(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.end,
                                        children: [
                                          Text(
                                            '$currency${regularEMI.toStringAsFixed(0)}',
                                            style: _cellStyle(context).copyWith(
                                              fontWeight: FontWeight.w600,
                                              color: Theme.of(
                                                context,
                                              ).colorScheme.primary,
                                            ),
                                          ),
                                          if (hasRemainder)
                                            Text(
                                              '1st: $currency${firstMonthEMI.toStringAsFixed(0)}',
                                              style: _cellStyle(context)
                                                  .copyWith(
                                                    fontSize: 10,
                                                    color:
                                                        Colors.green.shade700,
                                                  ),
                                            ),
                                        ],
                                      ),
                                    ),
                                  ],
                                ),
                              );
                            }),
                          ],
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),

                  // Payment Timeline Section
                  _buildSection(
                    context,
                    title: 'Payment Schedule',
                    icon: Icons.event_note_outlined,
                    children: [_buildPaymentTimeline(context, currency)],
                  ),
                  const SizedBox(height: 80),
                ],
              ),
            ),
          ),

          // Footer with buttons
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Theme.of(context).colorScheme.surface,
              border: Border(
                top: BorderSide(color: Theme.of(context).colorScheme.outline),
              ),
            ),
            child: Row(
              children: [
                Expanded(
                  child: OutlinedButton(
                    onPressed: () => Navigator.pop(context),
                    style: OutlinedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 14),
                      side: BorderSide(
                        color: Theme.of(context).colorScheme.outline,
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    child: Text(
                      'Edit',
                      style: GoogleFonts.inter(
                        fontSize: 15,
                        fontWeight: FontWeight.w600,
                        color: Theme.of(context).colorScheme.onSurface,
                      ),
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  flex: 2,
                  child: ElevatedButton(
                    onPressed: _isLoading ? null : _handleSubmit,
                    style: ElevatedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(vertical: 14),
                      backgroundColor: Theme.of(context).colorScheme.tertiary,
                      foregroundColor: Colors.white,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                      elevation: 0,
                    ),
                    child: _isLoading
                        ? const SizedBox(
                            width: 20,
                            height: 20,
                            child: CircularProgressIndicator(
                              color: Colors.white,
                              strokeWidth: 2,
                            ),
                          )
                        : Text(
                            widget.isEditMode
                                ? 'Update Chitti'
                                : 'Create Chitti',
                            style: GoogleFonts.inter(
                              fontSize: 15,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSection(
    BuildContext context, {
    required String title,
    required IconData icon,
    required List<Widget> children,
  }) {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Theme.of(context).colorScheme.surface,
        borderRadius: BorderRadius.circular(24),
        border: Border.all(
          color: Theme.of(context).colorScheme.outline.withOpacity(0.1),
        ),
        boxShadow: [
          BoxShadow(
            color: Theme.of(context).colorScheme.onSurface.withOpacity(0.03),
            offset: const Offset(0, 4),
            blurRadius: 12,
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: Theme.of(context).colorScheme.primary.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: Icon(
                  icon,
                  size: 18,
                  color: Theme.of(context).colorScheme.primary,
                ),
              ),
              const SizedBox(width: 12),
              Text(
                title,
                style: GoogleFonts.inter(
                  fontSize: 16,
                  fontWeight: FontWeight.w700,
                  color: Theme.of(context).colorScheme.onSurface,
                  letterSpacing: -0.5,
                ),
              ),
            ],
          ),
          const SizedBox(height: 20),
          ...children,
        ],
      ),
    );
  }

  Widget _buildInfoRow(BuildContext context, String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            label,
            style: GoogleFonts.inter(
              fontSize: 14,
              fontWeight: FontWeight.w500,
              color: Theme.of(context).colorScheme.onSurface.withOpacity(0.6),
            ),
          ),
          Flexible(
            child: Text(
              value,
              textAlign: TextAlign.end,
              style: GoogleFonts.inter(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: Theme.of(context).colorScheme.onSurface,
              ),
            ),
          ),
        ],
      ),
    );
  }

  /// Build payment timeline showing all payment dates
  Widget _buildPaymentTimeline(BuildContext context, String currency) {
    final (monthDates, monthNames) = CurrencyUtils.generateMonthDates(
      widget.startMonth,
      widget.duration,
    );
    final paymentDay = int.tryParse(widget.paymentDay) ?? 5;

    // Get selected gold option for EMI calculation
    final selectedOption = widget.goldOptions.firstWhere(
      (o) => o.id == _selectedOptionIdForSchedule,
      orElse: () => widget.goldOptions.first,
    );
    final totalValue = widget.totalCosts[selectedOption.id] ?? 0.0;
    final emiBreakdown = CurrencyUtils.getEMIBreakdown(
      totalValue,
      widget.duration,
    );
    final firstMonthEMI = emiBreakdown['firstMonth'] as double;
    final regularEMI = emiBreakdown['regularMonths'] as double;

    final colorScheme = Theme.of(context).colorScheme;

    return Column(
      children: [
        // Gold Option Selector
        if (widget.goldOptions.length > 1) ...[
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            padding: const EdgeInsets.only(bottom: 20, left: 4, right: 4),
            child: Row(
              children: widget.goldOptions.map((option) {
                final isSelected = option.id == _selectedOptionIdForSchedule;
                return Padding(
                  padding: const EdgeInsets.only(right: 8),
                  child: FilterChip(
                    selected: isSelected,
                    label: Text(
                      '${option.weight}g ${option.type}',
                      style: GoogleFonts.inter(
                        fontSize: 12,
                        fontWeight: isSelected
                            ? FontWeight.w700
                            : FontWeight.w500,
                        color: isSelected
                            ? colorScheme.onPrimary
                            : colorScheme.onSurface.withOpacity(0.6),
                      ),
                    ),
                    onSelected: (selected) {
                      if (selected) {
                        setState(() {
                          _selectedOptionIdForSchedule = option.id;
                        });
                      }
                    },
                    backgroundColor: colorScheme.surface,
                    selectedColor: colorScheme.primary,
                    checkmarkColor: colorScheme.onPrimary,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                      side: BorderSide(
                        color: isSelected
                            ? colorScheme.primary
                            : colorScheme.outline.withOpacity(0.1),
                      ),
                    ),
                    showCheckmark: false,
                    visualDensity: VisualDensity.compact,
                  ),
                );
              }).toList(),
            ),
          ),
        ],
        // Timeline header
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
          decoration: BoxDecoration(
            color: Theme.of(context).colorScheme.surfaceContainerHighest,
            borderRadius: const BorderRadius.vertical(top: Radius.circular(8)),
          ),
          child: Row(
            children: [
              Expanded(
                flex: 2,
                child: Text('Month', style: _headerStyle(context)),
              ),
              Expanded(
                flex: 2,
                child: Text(
                  'Payment Due',
                  style: _headerStyle(context),
                  textAlign: TextAlign.center,
                ),
              ),
              Expanded(
                child: Text(
                  'EMI',
                  style: _headerStyle(context),
                  textAlign: TextAlign.end,
                ),
              ),
            ],
          ),
        ),
        // Timeline rows
        Container(
          decoration: BoxDecoration(
            borderRadius: const BorderRadius.vertical(
              bottom: Radius.circular(8),
            ),
          ),
          child: monthDates.isEmpty
              ? Container(
                  padding: const EdgeInsets.all(24),
                  child: Center(
                    child: Text(
                      'Could not generate payment schedule.\nPlease check the start month format.',
                      textAlign: TextAlign.center,
                      style: GoogleFonts.inter(
                        fontSize: 13,
                        color: Theme.of(context).colorScheme.error,
                      ),
                    ),
                  ),
                )
              : ListView.separated(
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  itemCount: monthDates.length, // Safely use list length
                  separatorBuilder: (context, index) => Divider(
                    height: 1,
                    color: Theme.of(context).colorScheme.outline,
                  ),
                  itemBuilder: (context, index) {
                    final monthDate = monthDates[index];
                    final monthName = monthNames[index];
                    final paymentDueDate = DateTime(
                      monthDate.year,
                      monthDate.month,
                      paymentDay,
                    );
                    final formattedDueDate = DateFormat(
                      'd MMM yyyy',
                    ).format(paymentDueDate);
                    final emi = index == 0 ? firstMonthEMI : regularEMI;
                    final isFirstMonth =
                        index == 0 && firstMonthEMI != regularEMI;

                    return Container(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 16,
                        vertical: 14,
                      ),
                      child: Row(
                        children: [
                          // Month number and name
                          Expanded(
                            flex: 2,
                            child: Row(
                              children: [
                                Container(
                                  width: 32,
                                  height: 32,
                                  decoration: BoxDecoration(
                                    color: Theme.of(
                                      context,
                                    ).colorScheme.primary.withOpacity(0.1),
                                    borderRadius: BorderRadius.circular(10),
                                  ),
                                  alignment: Alignment.center,
                                  child: Text(
                                    '${index + 1}',
                                    style: GoogleFonts.inter(
                                      fontSize: 13,
                                      fontWeight: FontWeight.w700,
                                      color: Theme.of(
                                        context,
                                      ).colorScheme.primary,
                                    ),
                                  ),
                                ),
                                const SizedBox(width: 12),
                                Expanded(
                                  child: Text(
                                    monthName,
                                    style: _cellStyle(
                                      context,
                                    ).copyWith(fontWeight: FontWeight.w600),
                                  ),
                                ),
                              ],
                            ),
                          ),
                          // Payment due date
                          Expanded(
                            flex: 2,
                            child: Text(
                              formattedDueDate,
                              style: _cellStyle(context).copyWith(
                                color: Theme.of(
                                  context,
                                ).colorScheme.onSurface.withOpacity(0.6),
                              ),
                              textAlign: TextAlign.center,
                            ),
                          ),
                          // EMI amount
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.end,
                              children: [
                                Text(
                                  '$currency${emi.toStringAsFixed(0)}',
                                  style: _cellStyle(context).copyWith(
                                    fontWeight: FontWeight.w700,
                                    color: isFirstMonth
                                        ? Colors.green.shade800
                                        : Theme.of(
                                            context,
                                          ).colorScheme.onSurface,
                                  ),
                                ),
                                if (isFirstMonth &&
                                    (firstMonthEMI - regularEMI) > 0)
                                  Builder(
                                    builder: (context) {
                                      final remainder =
                                          firstMonthEMI - regularEMI;
                                      return Text(
                                        '+${remainder % 1 == 0 ? remainder.toInt().toString() : remainder.toStringAsFixed(2)}',
                                        style: GoogleFonts.inter(
                                          fontSize: 9,
                                          color: Colors.green.shade700,
                                        ),
                                      );
                                    },
                                  ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    );
                  },
                ),
        ),
      ],
    );
  }

  TextStyle _headerStyle(BuildContext context) {
    return GoogleFonts.inter(
      fontSize: 12,
      fontWeight: FontWeight.w700,
      color: Theme.of(context).colorScheme.onSurface.withOpacity(0.5),
      letterSpacing: 0.5,
    );
  }

  TextStyle _cellStyle(BuildContext context) {
    return GoogleFonts.inter(
      fontSize: 14,
      fontWeight: FontWeight.w500,
      color: Theme.of(context).colorScheme.onSurface,
    );
  }
}
